### ISSUE TITLE
Wrong URL in latest circle builds

### ISSUE THREAD

**Issue by adidahiya** [themadcreator/circle-github-bot#22]
seen in blueprint recently

[PR comment](https://github.com/palantir/blueprint/pull/3982#issuecomment-591598980)
- goes to wrong URL [https://30210-71939872-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html](https://30210-71939872-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html)
- should instead be the same URL without the `home/circleci/project/` part: [https://30210-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html](https://30210-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html)

**Comment by yfarjoun** [comment]
Please review and release a version with this fix... 🙏 our use of Circle-github-bot is suffering as the artifact links are broken....thanks!!!
